
let american_to_british = {
    'parentheses': 'brackets',
    'a head of lettuce': 'a lettuce',
    'a deck of cards': 'a pack of cards',
    'a pack of cigarettes': 'a packet of cigarettes',
    'gas pedal': 'accelerator',
    'accommodations': 'accommodation',
    'instant replay': 'action replay',
    'antenna': 'aerial (tv, radio)',
    'aerial': 'aerial (tv, radio)',
    'airfoil': 'aerofoil',
    'airplane': 'plane',
    'advice columnist': 'agony aunt',
    'allen wrench': 'allen key',
    'german shepherd': 'alsatian',
    'aluminum': 'aluminium',
    'native american': 'american indian',
    'anise': 'aniseed',
    'jacket': 'anorak',
    'parka': 'anorak',
    'counter-clockwise': 'anti-clockwise',
    'starter': 'appetizer',
    'tractor-trailer': 'articulated lorry',
    'trailer truck': 'articulated lorry',
    'uneven bars': 'asymmetric bars',
    'on the weekend': 'at the weekend',
    'eggplant': 'aubergine',
    'autumn, fall': 'autumn',
    'cookie sheet': 'baking tray',
    'legal holiday': 'bank holiday',
    'national holiday': 'bank holiday',
    'federal holiday': 'bank holiday',
    'lawyer': 'solicitor',
    'attorney': 'solicitor',
    'prime rate': 'base rate',
    'beet': 'beetroot',
    'check': 'bill',
    'garbage can': 'dustbin',
    'ball-point pen': 'biro',
    'cookie': 'biscuit',
    'cracker': 'biscuit',
    'underground economy': 'black economy',
    'sponge bath': 'blanket bath',
    'apartment building': 'block of flats',
    'coveralls': 'boiler suit',
    'hood': 'bonnet',
    'hat': 'bonnet (clothing)',
    'tube top': 'boob tube',
    'trunk (of a car)': 'boot',
    'trunk': 'boot',
    'hope chest': 'bottom drawer',
    'lawn bowling': 'bowls',
    'suspenders': 'braces',
    'headcheese': 'brawn (the food)',
    'tow truck': 'breakdown van',
    'cinder block': 'breeze block',
    'bridge loan': 'bridging loan',
    'fanny pack': 'bumbag',
    'cotton candy': 'candy floss',
    'parking lot': 'car park',
    'trailer': 'caravan',
    'janitor': 'caretaker',
    'emergency room': 'casualty',
    'catalog': 'catalogue',
    'slingshot': 'catapult',
    'median strip': 'central reservation',
    'center': 'centre',
    'drugstore': "chemist's shop",
    'pharmacy': "chemist's shop",
    'fries': 'chips',
    'french fries': 'chips',
    'movie theater': 'cinema',
    'the movies': 'cinema',
    'movies': 'cinema',
    'downtown': 'city centre',
    'city center': 'city centre',
    'plastic wrap': 'cling film',
    'checkroom': 'cloakroom',
    'coatroom': 'cloakroom',
    'clothespin': 'peg',
    'coffin': 'coffin',
    'casket': 'coffin',
    'color': 'colour',
    'harbor seal': 'common seal',
    'durable goods': 'consumer durables',
    'stove': 'cooker',
    'cornstarch': 'cornflour',
    'romaine': 'cos (lettuce)',
    'swimsuit': 'costume',
    'cozy': 'cosy',
    'crib': 'cot',
    'crib death': 'cot death',
    'cotton swab': 'cotton bud',
    'absorbent cotton': 'cotton wool',
    'cotton ball': 'cotton wool',
    '(housing) project': 'council estate',
    'zucchini': 'courgette',
    'face card': 'court card',
    'guardrail': 'crash barrier',
    'chips': 'crisps',
    'potato chips': 'crisps',
    'alligator clip': 'crocodile clip',
    'bias-ply': 'cross-ply',
    'crossroad (in the country)': 'crossroads',
    'intersection': 'crossroads',
    'crossroads (rural)': 'crossroads',
    'quarter note': 'crotchet (music)',
    'checking account': 'current account',
    'résumé': 'curriculum vitae (cv)',
    'curriculum vitae': 'curriculum vitae (cv)',
    'hazard pay': 'danger money',
    'defroster': 'demister (in a car)',
    'dial tone': 'dialling tone',
    'rhinestone': 'diamante',
    'tux': 'dinner jacket',
    'tuxedo': 'dinner jacket',
    'directory assistance': 'directory enquiries',
    'detour': 'diversion',
    'heavy cream': 'double cream',
    'draft': 'draught',
    'checkers': 'draughts (game)',
    'thumbtack': 'drawing-pin',
    'robe': 'dressing gown',
    'bathrobe': 'dressing gown',
    'drunk driving': 'drink driving',
    'liquor cabinet': 'drinks cupboard',
    'cocktail party': 'drinks party',
    "driver's license": 'driving licence',
    'divided highway': 'dual carriageway',
    'pacifier': 'dummy',
    'drop cloth': 'dust sheet',
    'trash can': 'dustbin',
    'garbage collector': 'dustman',
    'comforter': 'duvet',
    'ground wire': 'earth wire',
    'ground': 'earth(electrical)',
    'busy': 'engaged',
    'engine, motor': 'engine',
    'inquiry': 'enquiry',
    'real estate agent': 'estate agent',
    'realtor': 'estate agent',
    'station wagon': 'estate car',
    'everyplace': 'everywhere',
    'unlisted': 'ex-directory',
    'expiration date': 'expiry date',
    'parochial school': 'faith school',
    'costumes': 'fancy dress',
    'santa claus': 'father christmas',
    'favorite': 'favourite',
    'film': 'film',
    'movie': 'film',
    'fiscal year': 'financial year',
    'fire company': 'fire brigade',
    'fire department': 'fire service ',
    'fire company ': 'fire service',
    'second floor': 'first floor',
    'fish stick': 'fish finger',
    'fish-sticks': 'fish-fingers',
    'wall-to-wall carpeting': 'fitted carpet',
    'soda': 'fizzy drink',
    'face cloth': 'flannel',
    'wash cloth': 'flannel',
    '(flat: apartment with a single floor)': 'flannel',
    'apartment': 'flat',
    'flat': 'flat',
    'studio': 'flat',
    'flat tire': 'flat tyre',
    'flavor': 'flavour',
    'flextime': 'flexitime',
    'switchblade': 'flick knife',
    'overpass': 'flyover',
    'soccer': 'football',
    'sidewalk': 'pavement',
    'two weeks': 'fortnight',
    'bangs': 'fringe',
    'from monday to friday': 'from monday to friday',
    'from monday through friday (friday included)': 'from monday to friday',
    'period (punctuation)': 'full stop',
    'lawn  ': 'garden',
    'yard': 'garden',
    'gearshift': 'gear lever',
    'transmission': 'gearbox (car)',
    'leverage': 'gearing (finance)',
    "men's room": 'gents',
    'girl scout': 'girl guide',
    'freight train': 'goods train',
    'elementary school': 'primary school',
    'wax paper': 'greaseproof paper',
    'waxed paper': 'greaseproof paper',
    'green thumb': 'green fingers',
    'broiler': 'grill (noun)',
    'broil': 'grill (verb)',
    'first floor': 'ground floor',
    'ground floor (in public buildings)': 'ground floor',
    'groundskeeper': 'groundsman',
    'barrette': 'hairslide',
    'purse': 'handbag',
    'shoulder bag': 'handbag',
    'harbor': 'harbour',
    'hatrack': 'hatstand',
    'principal': 'headteacher',
    'bachelorette party': 'hen night',
    'main street': 'high street',
    'installment plan': 'hire purchase',
    'billboard': 'hoarding',
    'stovetop': 'hob',
    'field hockey': 'hockey',
    'carryall': 'holdall',
    'vacation': 'holiday',
    'vacationer': 'holidaymaker',
    'homey': 'homely',
    'convertible top': 'hood (car)',
    'vacuum cleaner': 'hoover',
    '(garden) hose': 'hosepipe',
    'hot flash': 'hot flush',
    'housing development': 'housing estate',
    'humor': 'humour',
    'sprinkles (for ice cream)': 'hundreds and thousands',
    'popsicle (trademark)': 'ice lolly',
    'confectioners’ sugar': 'icing sugar',
    'powdered sugar': 'icing sugar',
    'in the hospital': 'in hospital',
    'turn signal (on a car)': 'indicator',
    'turn signal': 'indicator (on a car)',
    'inseam': 'inside leg',
    'quotation marks': 'quotation marks',
    'baked potato': 'jacket potato',
    'preserves': 'jam',
    'jelly beans': 'jelly babies',
    'jewelery': 'jewellery',
    'joe blow': 'joe bloggs',
    'john q. public': 'joe public',
    'pitcher': 'jug',
    '18-wheeler': 'juggernaut',
    'rummage sale': 'jumble sale',
    'yard sale': 'jumble sale',
    'jumper cable': 'jump lead',
    'sweater': 'jumper',
    'doghouse': 'kennel',
    'kilometer': 'kilometre',
    'ladybug': 'ladybird',
    'grade crossing': 'level crossing',
    'elevator': 'lift',
    'liter': 'litre',
    'crossing guard': 'lollipop lady (or man)',
    'lollipop': 'lolly',
    'rest room ': 'loo',
    'slipcover': 'loose cover',
    'truck': 'lorry',
    'semi': 'lorry',
    'tractor': 'lorry',
    'lost and found': 'lost property',
    'bullhorn': 'loudhailer',
    'flatbed truck': 'low loader',
    'grab bag': 'lucky dip',
    'baggage car': 'luggage van',
    'raincoat': 'mackintosh',
    'crazy': 'mad',
    'insane': 'mad',
    'highway': 'motorway',
    'corn': 'maize',
    'ceo (chief executive officer)': 'managing director',
    'snow pea': 'mangetout',
    'truck farm': 'market garden',
    'railroad yard': 'marshalling yard',
    'mashed potatoes': 'mashed potato',
    'game': 'match',
    'math': 'maths',
    'paved road': 'metalled road',
    'odometer': 'milometer',
    'half note': 'minim  (music)',
    'cellphone': 'mobile (phone)',
    'monkeyshines': 'monkey tricks',
    'motorcycle': 'motorbike',
    'expressway': 'motorway',
    'mom': 'mum',
    'mommy': 'mummy',
    'diaper': 'nappy',
    'social security number': 'national insurance number',
    'tic-tack-toe': 'naughts and crosses',
    'pinwale': 'needlecord',
    'neighbor': 'neighbour',
    'newscaster': 'newsreader',
    'bill': 'note',
    'bulletin board': 'notice board',
    'tic-tac-toe': 'noughts and crosses',
    'license plate': 'registration plate',
    'liquor store': 'off-licence',
    'package store': 'off-licence',
    'open-pit mining': 'opencast mining',
    'common stock': 'ordinary share',
    'oven mitt': 'oven glove',
    'wading pool': 'paddling pool',
    'underpants': 'pants',
    'acetaminophen': 'paracetamol',
    'kerosine': 'paraffin',
    'part (in hair)': 'parting',
    'solitaire': 'patience',
    'pay envelope': 'pay packet',
    'crosswalk': 'zebra crossing',
    'valance': 'pelmet',
    'bell pepper': 'pepper',
    'pet peeve': 'pet hate',
    'gasoline': 'petrol',
    'gas': 'petrol',
    'phone booth': 'phone box',
    'physical therapy': 'physiotherapy',
    'jumper': 'pinafore dress',
    'dark chocolate': 'plain chocolate',
    'all-purpose flour': 'plain flour',
    'big dipper': 'plough',
    'allowance': 'pocket money',
    'turtleneck': 'polo neck',
    'reverse discrimination': 'positive discrimination',
    'mail': 'post',
    'zip code': 'postcode',
    'absentee ballot': 'postal vote',
    'mailbox': 'postbox',
    'mailman': 'postman',
    'mail carrier': 'postman',
    'letter carrier': 'postman',
    'potato chip': 'potato crisp',
    'electrical outlet': 'power point',
    'baby carriage': 'pram',
    'stroller': 'pushchair',
    'shrimp': 'prawn',
    'snap': 'press stud',
    'pushup': 'press-up',
    'gi': 'private soldier',
    'program': 'programme',
    'bar': 'pub',
    'private school': 'public school',
    'public transportation': 'public transport',
    'punching bag': 'punchbag',
    'baby buggy': 'pushchair',
    'utility pole': 'pylon',
    'estimator': 'quantity surveyor',
    'eighth note': 'quaver (music)',
    'line': 'queue',
    'buck': 'quid',
    'race car': 'racing car',
    'railroad': 'railway',
    'court tennis': 'real tennis',
    'front desk': 'reception',
    'certified mail': 'recorded delivery',
    'retread': 'remould (tyre)',
    'round-trip': 'return (ticket)',
    'collect call': 'reverse charge',
    'call collect': 'reverse the charges',
    'back-up lights': 'reversing lights',
    'right triangle': 'right-angled triangle',
    'beltway': 'ring road',
    'pavement': 'road way',
    'blacktop': 'road surface',
    'traffic circle': 'roundabout (in road)',
    'rotary': 'roundabout',
    'carousel': 'roundabout (at a fair)',
    'rowboat': 'rowing boat',
    'eraser': 'rubber',
    'garbage': 'rubbish',
    'backpack': 'rucksack',
    'sailboat': 'sailing boat',
    'sedan': 'saloon (car)',
    'sandbox': 'sandpit',
    'layer cake': 'sandwich cake',
    'sanitary napkin': 'sanitary towel',
    'self-rising flour': 'self-raising flour',
    'whole note': 'semibreve (music)',
    'half step': 'semitone (music)',
    'stock': 'share',
    'stock option': 'share option',
    'store': 'shop',
    'sales clerk': 'shop assistant',
    'shopping cart': 'trolley',
    'model home': 'show house',
    'nauseated': 'sick',
    'muffler': 'silencer (car)',
    'rump roast': 'silverside',
    'one-way': 'single (ticket)',
    'one-way ticket': 'single ticket',
    'skeleton in the closet': 'skeleton in the cupboard',
    'skim milk': 'skimmed milk',
    'jump rope': 'skipping rope',
    'baseboard': 'skirting board',
    'sled': 'sledge',
    'railroad tie': 'sleeper',
    'silent partner': 'sleeping partner',
    'slowpoke': 'slowcoach',
    'chutes and ladders': 'snakes and ladders',
    'excuse me': 'sorry',
    'soy': 'soya',
    'soybean': 'soya bean',
    'wrench': 'spanner',
    'backsplash': 'splashback',
    'fields day': 'sports day',
    'scallion': 'spring onion',
    'bachelor party': 'stag night',
    'utility knife': 'stanley knife',
    'appetizer': 'starter',
    'public school': 'state school',
    'inventory': 'stock',
    'tempest in a teapot': 'storm in a teacup',
    'underpass': 'subway',
    'raisin': 'sultana',
    'supertitle': 'surtitle',
    'rutabaga': 'swede',
    'candy store': 'sweet shop',
    'candy': 'sweets',
    'takeout': 'takeaway (food)',
    'to go': 'takeaway (food)',
    'faucet': 'tap',
    'cab': 'taxi',
    'taxi stand': 'taxi rank',
    'dish towel': 'tea towel',
    'television': 'telly ',
    'semester': 'term',
    'row house': 'terrace house',
    'theater': 'theatre',
    'liability insurance': 'third-party insurance',
    'check mark': 'tick',
    'scalper': 'ticket tout',
    'pantyhose': 'tights',
    'lumber': 'timber',
    'schedule': 'timetable',
    'can': 'tin',
    'tidbit': 'titbit',
    'to bathe': 'to bath',
    'to fill out': 'to fill in',
    'to rent': 'to hire',
    'to set the table': 'to lay the table',
    'to line up': 'to queue',
    'to call': 'to ring',
    'wash up': 'to wash',
    'candy apple': 'toffee apple',
    'caramel apple': 'toffee apple',
    'bathroom': 'toilet',
    'toll road': 'toll motorway',
    'turnpike': 'toll motorway',
    'flashlight': 'torch',
    'knock on wood': 'touch wood',
    'labor union': 'trade union',
    'industrial park': 'trading estate',
    'sneakers': 'trainers',
    'streetcar': 'tram',
    'truck stop': 'transport cafe',
    'traveled': 'travelled',
    'cart': 'trolley',
    'pants': 'trousers',
    'subway': 'underground',
    'twelve-gauge': 'twelve-bore',
    'tire': 'tyre',
    'carpet pad': 'underlay',
    'mortician': 'undertaker',
    'college': 'university',
    'thermos bottle': 'vacuum flask',
    'shoulder': 'verge (of a road)',
    'undershirt': 'vest',
    'veterinarian': 'veterinary surgeon',
    'car': 'wagon(on a train)',
    'vest': 'waistcoat',
    'walker': 'walking frame',
    'billfold': 'wallet',
    'closet': 'wardrobe',
    'italian ice': 'water ice',
    'clapboard': 'weatherboard',
    'rubber boots': 'wellington boots',
    'rain boots': 'wellington boots',
    'coffee with cream': 'white coffee',
    'mineral spirits': 'white spirit',
    'wholewheat bread': 'wholemeal bread',
    'windbreaker': 'windcheater',
    'windshield': 'windscreen',
    'fender': 'wing',
    'countertop': 'worktop',
    'grade': 'year',
    'zee': 'zed(letter z)',
    'zipper': 'zip'
}

let british_to_american = {
    'brackets': 'parentheses',
    'a lettuce': 'a head of lettuce',
    'a pack of cards': 'a deck of cards',
    'a packet of cigarettes': 'a pack of cigarettes',
    'accelerator': 'gas pedal',
    'accommodation': 'accommodations',
    'action replay': 'instant replay',
    'aerial (TV, radio)': 'aerial',
    'aerofoil': 'airfoil',
    'aeroplane': 'airplane',
    'agony aunt': 'advice columnist',
    'Allen key': 'Allen wrench',
    'Alsatian': 'German shepherd',
    'aluminium': 'aluminum',
    'American Indian': 'Native American',
    'aniseed': 'anise',
    'anorak': 'parka',
    'anti-clockwise': 'counter-clockwise',
    'appetizer': 'starter',
    'articulated lorry': 'trailer truck',
    'asymmetric bars': 'uneven bars',
    'at the weekend': 'on the weekend',
    'aubergine': 'eggplant',
    'autumn': 'autumn, fall',
    'baking tray': 'cookie sheet',
    'bank holiday': 'federal holiday',
    'barrister': 'attorney',
    'base rate': 'prime rate',
    'beetroot': 'beet',
    'bill': 'check',
    'bin': 'garbage can',
    'biro': 'ball-point pen',
    'biscuit': 'cracker',
    'black economy': 'underground economy',
    'blanket bath': 'sponge bath',
    'block of flats': 'apartment building',
    'boiler suit': 'coveralls',
    'bonnet': 'hood',
    'bonnet (clothing)': 'hat',
    'boob tube': 'tube top',
    'boot': 'trunk',
    'bottom drawer': 'hope chest',
    'bowls': 'lawn bowling',
    'braces': 'suspenders',
    'brawn (the food)': 'headcheese',
    'breakdown van': 'tow truck',
    'breeze block': 'cinder block',
    'bridging loan': 'bridge loan',
    'bumbag': 'fanny pack',
    'candy floss': 'cotton candy',
    'car park': 'parking lot',
    'caravan': 'trailer',
    'caretaker': 'janitor',
    'casualty': 'emergency room',
    'catalogue': 'catalog',
    'catapult': 'slingshot',
    'central reservation': 'median strip',
    'centre': 'center',
    'chemist': 'drugstore',
    "chemist's shop": 'pharmacy',
    'chips': 'French fries',
    'cinema': 'movies',
    'city centre': 'city center',
    'cling film': 'plastic wrap',
    'cloakroom': 'coatroom',
    'clothes peg': 'clothespin',
    'coffin': 'casket',
    'colour': 'color',
    'common seal': 'harbor seal',
    'consumer durables': 'durable goods',
    'cooker': 'stove',
    'cornflour': 'cornstarch',
    'cos (lettuce)': 'Romaine',
    'costume': 'swimsuit',
    'cosy': 'cozy',
    'cot': 'crib',
    'cot death': 'crib death',
    'cotton bud': 'cotton swab',
    'cotton wool': 'cotton ball',
    'council estate': '(housing) project',
    'courgette': 'zucchini',
    'court card': 'face card',
    'crash barrier': 'guardrail',
    'crisps': 'potato chips',
    'crocodile clip': 'alligator clip',
    'cross-ply': 'bias-ply',
    'crossroads': 'crossroads (rural)',
    'crotchet (music)': 'quarter note',
    'current account': 'checking account',
    'curriculum vitae (CV)': 'curriculum vitae',
    'danger money': 'hazard pay',
    'demister (in a car)': 'defroster',
    'dialling tone': 'dial tone',
    'diamante': 'rhinestone',
    'dinner jacket': 'tuxedo',
    'directory enquiries': 'directory assistance',
    'diversion': 'detour',
    'double cream': 'heavy cream',
    'draught': 'draft',
    'draughts': 'checkers',
    'draughts (game)': 'checkers',
    'drawing-pin': 'thumbtack',
    'dressing gown': 'bathrobe',
    'drink driving': 'drunk driving',
    'drinks cupboard': 'liquor cabinet',
    'drinks party': 'cocktail party',
    'driving licence': "driver's license",
    'dual carriageway': 'divided highway',
    'dummy': 'pacifier',
    'dust sheet': 'drop cloth',
    'dustbin': 'trash can',
    'dustman': 'garbage collector',
    'duvet': 'comforter',
    'earth wire': 'ground wire',
    'earth(electrical)': 'ground',
    'engaged': 'busy',
    'engine': 'engine, motor',
    'enquiry': 'inquiry',
    'estate agent': 'real estate agent',
    'estate car': 'station wagon',
    'everywhere': 'everyplace',
    'ex-directory': 'unlisted',
    'expiry date': 'expiration date',
    'faith school': 'parochial school',
    'fancy dress': 'costumes',
    'Father Christmas': 'Santa Claus',
    'favourite': 'favorite',
    'film': 'movie',
    'financial year': 'fiscal year',
    'fire brigade': 'fire department',
    'fire brigade ': 'fire department',
    'fire service': 'fire company ',
    'fire service ': 'fire department',
    'first floor': 'second floor',
    'fish finger': 'fish stick',
    'fish-fingers': 'fish-sticks',
    'fitted carpet': 'wall-to-wall carpeting',
    'fizzy drink': 'soda',
    'flannel': '(flat: apartment with a single floor)',
    'flat': 'studio',
    'flat tyre': 'flat tire',
    'flavour': 'flavor',
    'flexitime': 'flextime',
    'flick knife': 'switchblade',
    'flyover': 'overpass',
    'football': 'soccer',
    'footway': 'sidewalk',
    'fortnight': 'two weeks',
    'fringe': 'bangs',
    'from Monday to Friday': 'from Monday through Friday (Friday included)',
    'full stop': 'period (punctuation)',
    'garden': 'yard',
    'gear lever': 'gearshift',
    'gearbox (car)': 'transmission',
    'gearing (finance)': 'leverage',
    'Gents': "Men's Room",
    'Girl Guide': 'Girl Scout',
    'goods train': 'freight train',
    'grade school': 'elementary school',
    'greaseproof paper': 'waxed paper',
    'green fingers': 'green thumb',
    'grill (noun)': 'broiler',
    'grill (verb)': 'broil',
    'ground floor': 'ground floor (in public buildings)',
    'groundsman': 'groundskeeper',
    'hairslide': 'barrette',
    'handbag': 'shoulder bag',
    'harbour': 'harbor',
    'hatstand': 'hatrack',
    'headmaster': 'principal',
    'headteacher': 'principal',
    'hen night': 'bachelorette party',
    'high street': 'main street',
    'hire purchase': 'installment plan',
    'hoarding': 'billboard',
    'hob': 'stovetop',
    'hockey': 'field hockey',
    'holdall': 'carryall',
    'holiday': 'vacation',
    'holidaymaker': 'vacationer',
    'homely': 'homey',
    'hood (car)': 'convertible top',
    'hoover': 'vacuum cleaner',
    'hosepipe': '(garden) hose',
    'hot flush': 'hot flash',
    'housing estate': 'housing development',
    'humour': 'humor',
    'hundreds and thousands': 'sprinkles (for ice cream)',
    'ice lolly': 'Popsicle (trademark)',
    'icing sugar': 'powdered sugar',
    'in hospital': 'in the hospital',
    'indicator': 'turn signal (on a car)',
    'indicator (on a car)': 'turn signal',
    'inside leg': 'inseam',
    'inverted commas': 'quotation marks',
    'jacket potato': 'baked potato',
    'jam': 'preserves',
    'jelly babies': 'jelly beans',
    'jewellery': 'jewelery',
    'Joe Bloggs': 'Joe Blow',
    'Joe Public': 'John Q. Public',
    'jug': 'pitcher',
    'juggernaut': '18-wheeler',
    'jumble sale': 'yard sale',
    'jump lead': 'jumper cable',
    'jumper': 'sweater',
    'junior school': 'elementary school',
    'kennel': 'doghouse',
    'kilometre': 'kilometer',
    'ladybird': 'ladybug',
    'level crossing': 'grade crossing',
    'lift': 'elevator',
    'litre': 'liter',
    'lollipop lady (or man)': 'crossing guard',
    'lolly': 'lollipop',
    'loo': 'rest room ',
    'loose cover': 'slipcover',
    'lorry': 'tractor',
    'lost property': 'lost and found',
    'loudhailer': 'bullhorn',
    'low loader': 'flatbed truck',
    'lucky dip': 'grab bag',
    'luggage van': 'baggage car',
    'mackintosh': 'raincoat',
    'mad': 'insane',
    'main road': 'highway',
    'maize': 'corn',
    'managing director': 'CEO (chief executive officer)',
    'mangetout': 'snow pea',
    'market garden': 'truck farm',
    'marshalling yard': 'railroad yard',
    'mashed potato': 'mashed potatoes',
    'match': 'game',
    'maths': 'math',
    'metalled road': 'paved road',
    'milometer': 'odometer',
    'minim  (music)': 'half note',
    'mobile (phone)': 'cellphone',
    'monkey tricks': 'monkeyshines',
    'motorbike': 'motorcycle',
    'motorway': 'highway',
    'mum': 'mom',
    'mummy': 'mommy',
    'nappy': 'diaper',
    'national insurance number': 'social security number',
    'naughts and crosses': 'tic-tack-toe',
    'needlecord': 'pinwale',
    'neighbour': 'neighbor',
    'newsreader': 'newscaster',
    'note': 'bill',
    'notice board': 'bulletin board',
    'noughts and crosses': 'tic-tac-toe',
    'number plate': 'license plate',
    'off-licence': 'package store',
    'opencast mining': 'open-pit mining',
    'ordinary share': 'common stock',
    'oven glove': 'oven mitt',
    'paddling pool': 'wading pool',
    'pants': 'underpants',
    'paracetamol': 'acetaminophen',
    'paraffin': 'kerosine',
    'parting': 'part (in hair)',
    'patience': 'solitaire',
    'pavement': 'sidewalk',
    'pay packet': 'pay envelope',
    'pedestrian crossing': 'crosswalk',
    'peg': 'clothespin',
    'pelmet': 'valance',
    'pepper': 'bell pepper',
    'pet hate': 'pet peeve',
    'petrol': 'gas',
    'phone box': 'phone booth',
    'physiotherapy': 'physical therapy',
    'pinafore dress': 'jumper',
    'plain chocolate': 'dark chocolate',
    'plain flour': 'all-purpose flour',
    'plane': 'airplane',
    'Plough': 'Big Dipper',
    'pocket money': 'allowance',
    'polo neck': 'turtleneck',
    'positive discrimination': 'reverse discrimination',
    'post': 'mail',
    'post code': 'zip code',
    'postal vote': 'absentee ballot',
    'postbox': 'mailbox',
    'postcode': 'zip code',
    'postman': 'letter carrier',
    'potato crisp': 'potato chip',
    'power point': 'electrical outlet',
    'pram': 'stroller',
    'prawn': 'shrimp',
    'press stud': 'snap',
    'press-up': 'pushup',
    'primary school': 'elementary school',
    'private soldier': 'GI',
    'programme': 'program',
    'pub': 'bar',
    'public school': 'private school',
    'public transport': 'public transportation',
    'punchbag': 'punching bag',
    'pushchair': 'baby buggy',
    'pylon': 'utility pole',
    'quantity surveyor': 'estimator',
    'quaver (music)': 'eighth note',
    'queue': 'line',
    'quid': 'buck',
    'quotation marks': 'quotation marks',
    'racing car': 'race car',
    'railway': 'railroad',
    'real tennis': 'court tennis',
    'reception': 'front desk',
    'recorded delivery': 'certified mail',
    'registration plate': 'license plate',
    'remould (tyre)': 'retread',
    'return (ticket)': 'round-trip',
    'reverse charge': 'collect call',
    'reverse the charges': 'call collect',
    'reversing lights': 'back-up lights',
    'right-angled triangle': 'right triangle',
    'ring road': 'beltway',
    'road surface': 'blacktop',
    'road way': 'pavement',
    'roundabout': 'rotary',
    'roundabout (at a fair)': 'carousel',
    'roundabout (in road)': 'traffic circle',
    'rowing boat': 'rowboat',
    'rubber': 'eraser',
    'rubbish': 'garbage',
    'rucksack': 'backpack',
    'sailing boat': 'sailboat',
    'saloon (car)': 'sedan',
    'sandpit': 'sandbox',
    'sandwich cake': 'layer cake',
    'sanitary towel': 'sanitary napkin',
    'self-raising flour': 'self-rising flour',
    'semibreve (music)': 'whole note',
    'semitone (music)': 'half step',
    'share': 'stock',
    'share option': 'stock option',
    'shop': 'store',
    'shop assistant': 'sales clerk',
    'shopping trolley': 'shopping cart',
    'show home': 'model home',
    'show house': 'model home',
    'sick': 'nauseated',
    'silencer (car)': 'muffler',
    'silverside': 'rump roast',
    'single (ticket)': 'one-way',
    'single ticket': 'one-way ticket',
    'skeleton in the cupboard': 'skeleton in the closet',
    'skimmed milk': 'skim milk',
    'skipping rope': 'jump rope',
    'skirting board': 'baseboard',
    'sledge': 'sled',
    'sleeper': 'railroad tie',
    'sleeping partner': 'silent partner',
    'slowcoach': 'slowpoke',
    'snakes and ladders': 'chutes and ladders',
    'solicitor': 'attorney',
    'Sorry': 'Excuse me',
    'soya': 'soy',
    'soya bean': 'soybean',
    'spanner': 'wrench',
    'splashback': 'backsplash',
    'sports day': 'fields day',
    'spring onion': 'scallion',
    'stag night': 'bachelor party',
    'Stanley knife': 'utility knife',
    'starter': 'appetizer',
    'state school': 'public school',
    'stock': 'inventory',
    'storm in a teacup': 'tempest in a teapot',
    'subway': 'underpass',
    'sultana': 'raisin',
    'surtitle': 'supertitle',
    'swede': 'rutabaga',
    'sweet shop': 'candy store',
    'sweets': 'candy',
    'takeaway (food)': 'to go',
    'tap': 'faucet',
    'taxi': 'cab',
    'taxi rank': 'taxi stand',
    'tea towel': 'dish towel',
    'telly ': 'television',
    'term': 'semester',
    'terrace house': 'row house',
    'theatre': 'theater',
    'third-party insurance': 'liability insurance',
    'tick': 'check mark',
    'ticket tout': 'scalper',
    'tights': 'pantyhose',
    'timber': 'lumber',
    'timetable': 'schedule',
    'tin': 'can',
    'titbit': 'tidbit',
    'to bath': 'to bathe',
    'to fill in': 'to fill out',
    'to hire': 'to rent',
    'to lay the table': 'to set the table',
    'to queue': 'to line up',
    'to ring': 'to call',
    'to wash': 'wash up',
    'toffee apple': 'caramel apple',
    'toilet': 'bathroom',
    'toll motorway': 'turnpike',
    'torch': 'flashlight',
    'touch wood': 'knock on wood',
    'trade union': 'labor union',
    'trading estate': 'industrial park',
    'trainers': 'sneakers',
    'tram': 'streetcar',
    'transport cafe': 'truck stop',
    'travelled': 'traveled',
    'trolley': 'cart',
    'trousers': 'pants',
    'tube': 'subway',
    'twelve-bore': 'twelve-gauge',
    'tyre': 'tire',
    'underground': 'subway',
    'underlay': 'carpet pad',
    'undertaker': 'mortician',
    'university': 'college',
    'vacuum flask': 'thermos bottle',
    'verge (of a road)': 'shoulder',
    'vest': 'undershirt',
    'veterinary surgeon': 'veterinarian',
    'wagon(on a train)': 'car',
    'waistcoat': 'vest',
    'walking frame': 'walker',
    'wallet': 'billfold',
    'wardrobe': 'closet',
    'water ice': 'Italian ice',
    'weatherboard': 'clapboard',
    'wellington boots': 'rain boots',
    'white coffee': 'coffee with cream',
    'white spirit': 'mineral spirits',
    'wholemeal bread': 'wholewheat bread',
    'windcheater': 'windbreaker',
    'windscreen': 'windshield',
    'wing': 'fender',
    'worktop': 'countertop',
    'year': 'grade',
    'zebra crossing': 'crosswalk',
    'zed(letter Z)': 'zee',
    'zip': 'zipper'
}


function find_cap_chars(word) {
	let caps_list = [];
	for (let char in word) {
		if (word.charAt(char) == word.charAt(char).toLowerCase()) {
			continue;
		} else {
			if (char.length == 1) {
				caps_list.push(char);
			}
		}
	}
	return caps_list;
}


// need some sort of indicator for which direction we want to switch the language to
let to_american = true;


let dictionary;
if (to_american == true) {
	dictionary = american_to_british;
} else {
	dictionary = british_to_american;
}


var elements = document.body.getElementsByTagName("*");

for (var i = 0; i < elements.length; i++) {
	var current = elements[i];
	if (current.tagName != "SCRIPT" && current.tagName != "STYLE") {
		if (current.children.length === 0 && current.textContent.replace(/ |\n/g,'') !== '') {
			let words = current.innerText;
			try {
				words = words.split(" ");
			} catch {
				continue;
			}
			
			let updated_words = "";
			for (let word of words) {
				if (dictionary[word.toLowerCase()]) {
					let cap_letters = find_cap_chars(word);
					let final_new_word = "";
					let temp_new_word = "";
					if (cap_letters.length > 1) {
						//all caps
						final_new_word = dictionary[word.toLowerCase()].toUpperCase();
					} else if (cap_letters.length == 1 && cap_letters[0] == 0) {
						//first letter caps
						temp_new_word = dictionary[word.toLowerCase()];
						final_new_word = temp_new_word.charAt(0).toUpperCase() + temp_new_word.substring(1, temp_new_word.length);
					} else {
						final_new_word = dictionary[word.toLowerCase()]
					}

					updated_words = updated_words + final_new_word + " ";
					console.log("[-] " + word);
					console.log("[+] " + final_new_word);
				} else {
					updated_words = updated_words + word + " ";
				}
			}
			current.innerText = updated_words;
		}
	}
}

